### PR TITLE
Arm64 builds

### PR DESCRIPTION
**Pull request by leonitousconforti**
Emulator somewhat working on arm64.

I managed to find a place to get the arm64 emulator binaries. From the android studio editor release notes on August 16, 2020 (**https://developer.android.com/studio/releases/emulator#emulator_for_arm64_hosts**) it says your can now build the Emulator for ARM64 hosts - "Linux emulator source code now supports cross compilation from x86_64 to arm64 hosts, enabling running arm64 system images with KVM virtualization."

I took my jetson nano (as that is the platform I am interested in running this on) and flashed a fresh sd card installation following the jetson getting started pages as it had been a while since I booted it up. I also needed to install python3 and the google source REPO tool which was unsuccessful when I did it through `sudo apt-get install repo` so I had to install it using the manual method.

Then, I checked out the android source repository following the instructions from the release notes. Unfortunately, even with a 64GB sd card and a fresh installation with nothing else installed, the sd card ran out of space when it was checking out all the files. The next day, I did the same steps on my ubuntu x86 machine, as the release notes also state that you can cross compile from x64 to arm64. This time I had enough space to check out the repository, just a heads up, it was over 50GB in total. I attempted to build the Emulator targeting arm64, but it failed on some tests and I am not sure why. I found another page that listed some dependencies to install before building, so I installed them and tried again. 

In the time that it spent building, which was multiple hours before it would fail, I came across another github issue (**https://github.com/google/android-emulator-container-scripts/issues/192**).  Reading this, I discovered that you can in fact download the prebuilt arm64 emulator binaries from the android CI artifact server. You want the "aosp-emu-master-dev" branch, aosp is android open source project. **https://ci.android.com/builds/branches/aosp-emu-master-dev/grid**. From arm64 emulator is under the linux_aarch64 heading in the emulator section, and you can download the lastest passing build which will be a green box. The link I used was **https://ci.android.com/builds/submitted/8574552/emulator-linux_aarch64/latest** and then clicked on sdk-repo-linux_aarch64-emulator-8574552.zip (its ~2GB btw). 

I setup a docker image following this readme, and only installed "platform-tools" and "platforms;android-31" from the sdk manager. I manually extracted and moved the contents of the sdk-repo-linux_aarch64-emulator-8574552.zip to sdk/emulator. I then tried to install the "system-images;android-31;default;arm64-v8a" system image, but the sdkmanager kept refusing to because the emulator dependency was not installed - something like "error: missing emulator dependency not found." I tried to find a way to trick/prove to the sdkmanager that the emulator package was installed but I could not find any way of doing this. So I resorted to trying to download a system image manually. I found this website: **https://androidsdkmanager.azurewebsites.net/AndroidSystemImages** which seems a little sketch, however, all the links on the website are dl.google.com links so I went ahead and downloaded the ARM 64 v8a System Image api 31. The direct link is **https://dl.google.com/android/repository/sys-img/android/arm64-v8a-31_r03.zip**. I then extracted and moved the contents of the zip to sdk/system-images/android-31/default/arm64-v8a.

Next, I tried to make an emulator using the commands from the readme, but after prompting if I wanted to created a new hardware profile, the avdmanager also failed with error "error: missing emulator dependency not found." I resorted to created the emulator manually. This comment from the other github issue helped a lot: **https://github.com/google/android-emulator-container-scripts/issues/192#issuecomment-885198418**. I needed to create three files, advancedFeatures.ini, config.ini, and test.ini to create the avd. You can see them in the changed files in the pull request.

In the end, I was able to start the emulator using a modified command: ```emulator @test -no-audio -no-boot-anim -no-window -gpu swiftshader_indirect -qemu -cpu max -machine gic-version=max```

I followed the instructions for the vnc docker image and built that as well, and was able to start the emulator using the same command but without the -no-window argument. unfortunately, the window does not seem to render correctly, It is a mangled black screen right now but it definitely shows up. When I close the emulator the "saving state" ui element seems to fix some of the other mangled UI elements for some reason. Will look into getting the window to render properly over vnc later but it is a start.

### CODE REVIEW

**Comment by leonitousconforti** [comment]
The git lfs objects did not upload (which is probably a good thing now that I think about it) because this is a fork and github disables creating new lfs objects on forks. So you will have to download the emulator binaries and system images yourself.

**Comment by yaizudamashii** [comment]
Hi @leonitousconforti thank you so much for your investigation.  I tried what you wrote, and was able to run emulator on ARM Ubunt 20.04 on AWS.  The emulator doesn't work as it is supposed to, but it is a big step forward that we were able to get to a point where we can run an emulator, thank you for figuring all that out.

I've tried three different ci build artifacts for aarch64, [7176368](https://ci.android.com/builds/submitted/7176368/aarch64_sdk_tools_linux/latest), [8574552](https://ci.android.com/builds/submitted/8574552/emulator-linux_aarch64/latest), and [8572378](https://ci.android.com/builds/submitted/8572378/emulator-linux_aarch64/latest).  Out of those, 8572378 which happened to the first build I tried, worked the best, as in that some window showed up with starting animation while the other two builds didn't.  

ezgif com-gif-maker

My hopes are not so high that we will have a working build as they are just artifacts of some people developing on the android team and if they do have working arm Linux build, they would publish it...

I won't merge this PR for now, but will keep it open for updates in the future.  Once we get a working solution I will merge, then also publish a PR to the original repo.

**Comment by yaizudamashii** [comment]
Tried adding 
`GLDirectMem = on` to `advancedFeatures.ini` as per
https://docs.microsoft.com/en-us/answers/questions/465493/android-emulator-vulkan-1dll-not-found.html
but got the same result.

**Comment by victorccaldas** [comment]
Hey any luck? Wish I could help on these testings but they are just too complicated to me.

**Pull request closed without merging**
